name: CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Package
      run: perl -0pe 's/.*Packaging.*?```sh(.*?)```.*/\1/s' README.md | sh
    - name: Artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        name: pkg
        path: pkg.deb
